Feature/user detail
timothypartaliano/blood-nation-backend pull request #3
Opened 2024-04-30 06:21 UTC by timothypartaliano

add GET user detail API, add pagination & offset in GET all events, add cors for FE

2024-04-30 07:02 UTC, rickydbithealth requested changes

2024-04-30 07:02 UTC, rickydbithealth commented on controllers/userController.js
> +                console.error(err);
pastikan errornya dimasking

2024-04-30 07:06 UTC, rpratama-sho approved these changes

2024-05-02 02:25 UTC, haikal-handamara-x150s approved these changes

2024-05-07 10:13 UTC, rickydbithealth approved these changes

2024-05-07 10:15 UTC, merged